# Generated by Django 5.0.7 on 2024-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_acc',
            fields=[
                ('admin_acc_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('admin_username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_acc',
            fields=[
                ('student_acc_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('student_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('plp_email', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
