# Generated by Django 5.0.7 on 2024-10-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0003_alter_section_section'),
        ('userLogin', '0006_admin_acc_dept_id_admin_acc_is_mis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_acc',
            name='dept_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SET.department'),
        ),
    ]
