# Generated by Django 5.0.7 on 2024-10-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0009_alter_student_acc_plp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_acc',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='admin_acc',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='admin_acc',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admin_acc',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='student_acc',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='student_acc',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='student_acc',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student_acc',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='admin_acc',
            name='is_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admin_acc',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_acc',
            name='plp_email',
            field=models.EmailField(default='example_example@plpasig.edu.ph', max_length=254),
        ),
    ]
