# Generated by Django 3.2 on 2024-11-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0010_remove_admin_acc_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_acc',
            name='is_counted',
            field=models.BooleanField(default=False),
        ),
    ]
