# Generated by Django 5.0.7 on 2024-11-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0012_remove_student_acc_is_counted'),
    ]

    operations = [
        migrations.CreateModel(
            name='prof_acc',
            fields=[
                ('prof_acc_number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('plp_email', models.EmailField(default='example_example@plpasig.edu.ph', max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
