# Generated by Django 5.0.7 on 2024-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_data',
            fields=[
                ('training_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_feedback', models.CharField(max_length=255)),
                ('label', models.IntegerField()),
            ],
        ),
    ]
