from django.contrib import admin
from reportsAnalysis.models import filtered_feedbacks, RecurringPhrase, training_data, processed_feedbacks, college_numerical_total, college_feedback_total, college_numerical_summary_questions, college_feedback_summary, college_numerical_summary, professor_feedback_total, professor_numerical_total, professor_numerical_summary_category, professor_numerical_summary_questions, professor_feedback_summary

admin.site.register(filtered_feedbacks)
admin.site.register(training_data)
admin.site.register(processed_feedbacks)
admin.site.register(college_feedback_summary)
admin.site.register(college_feedback_total)
admin.site.register(college_numerical_summary)
admin.site.register(college_numerical_summary_questions)
admin.site.register(college_numerical_total)
admin.site.register(professor_feedback_total)
admin.site.register(professor_feedback_summary)
admin.site.register(professor_numerical_total)
admin.site.register(professor_numerical_summary_category)
admin.site.register(professor_numerical_summary_questions)
admin.site.register(RecurringPhrase)
