# Generated by Django 5.0.7 on 2024-09-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SET.department'),
        ),
    ]
