# Generated by Django 5.0.7 on 2024-09-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0002_programs_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=10),
        ),
    ]
