# Generated by Django 5.0.7 on 2024-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0004_subjects_assoc_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
