# Generated by Django 5.0.7 on 2024-10-09 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0007_delete_filtered_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numerical_ratings',
            name='numerical_date',
        ),
        migrations.AddField(
            model_name='numerical_ratings',
            name='numerical_rating_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
