# Generated by Django 5.0.7 on 2024-10-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0010_alter_student_enrolled_subjs_student_enrolled_subj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor_subjs',
            name='prof_subjects_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
