# Generated by Django 5.0.7 on 2024-10-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0012_alter_feedbacks_feedback_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='pre_processed_text',
        ),
    ]
