# Generated by Django 3.2 on 2024-10-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0013_remove_feedbacks_pre_processed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_info',
            name='extension_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
