# Generated by Django 3.2 on 2024-10-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0014_student_info_extension_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_questions',
            name='feedback_question_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
