# Generated by Django 3.2 on 2024-10-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0015_alter_feedback_questions_feedback_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor_info',
            name='extension_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
