# Generated by Django 3.2 on 2024-11-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0016_professor_info_extension_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('year_semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student_info',
            name='is_counted',
            field=models.BooleanField(default=False),
        ),
    ]
