# Generated by Django 3.2 on 2024-11-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0017_auto_20241101_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_sem_id', models.CharField(max_length=20)),
                ('total_students', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredAccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_registered_accounts', models.IntegerField(default=0)),
            ],
        ),
    ]
