# Generated by Django 3.2 on 2024-11-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0018_enrollmentsummary_registeredaccountsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentsummary',
            name='year_sem_id',
        ),
    ]
