# Generated by Django 3.2 on 2024-11-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0019_remove_enrollmentsummary_year_sem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submissions', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
