# Generated by Django 3.2 on 2024-11-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0020_submissionsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrollmentSummary',
        ),
        migrations.DeleteModel(
            name='RegisteredAccountSummary',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='is_counted',
        ),
    ]
