# Use the official Python image
FROM python:3.12-slim

# Install MySQL development dependencies
RUN apt-get update && apt-get install -y \
    libmysqlclient-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV MYSQLCLIENT_CFLAGS=-I/usr/include/mysql
ENV MYSQLCLIENT_LDFLAGS=-L/usr/lib/mysql

# Set up the application environment
WORKDIR /backendSet

# Copy and install dependencies
COPY requirements.txt /backendSet/
RUN pip install -r requirements.txt

# Copy the rest of the application files
COPY . /backendSet

# Expose the application port
EXPOSE 8000

# Run the Django application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
