# Generated by Django 5.0.7 on 2024-07-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
