# Generated by Django 5.0.7 on 2024-09-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academic_year',
            fields=[
                ('acad_year', models.CharField(default='24-25', max_length=6, primary_key=True, serialize=False)),
                ('academic_year_desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('category_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('department_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_questions',
            fields=[
                ('feedback_question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='professor_status',
            fields=[
                ('professor_status_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('professor_status_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='programs',
            fields=[
                ('program_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('program_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_status',
            fields=[
                ('student_status_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('student_status_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subject_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='year_level',
            fields=[
                ('year_level_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('year_level_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='academic_yearsem',
            fields=[
                ('year_sem_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('semester_desc', models.CharField(max_length=100)),
                ('acad_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='SET.academic_year')),
            ],
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('pre_processed_text', models.TextField(default='this is a pre_processed text.')),
                ('feedback_date', models.DateField()),
                ('feedback_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='SET.feedback_questions')),
            ],
        ),
        migrations.CreateModel(
            name='filtered_feedbacks',
            fields=[
                ('sentiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentiment_rating', models.IntegerField()),
                ('sentiment_label', models.CharField(max_length=12)),
                ('analysis_date', models.DateField(null=True)),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtered_feedbacks', to='SET.feedbacks')),
            ],
        ),
        migrations.CreateModel(
            name='numerical_questions',
            fields=[
                ('numerical_question_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerical_questions', to='SET.categories')),
            ],
        ),
        migrations.CreateModel(
            name='professor_info',
            fields=[
                ('professor_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('is_dean', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='SET.department')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='SET.professor_status')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('section_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=3)),
                ('program', models.ForeignKey(default='PLP', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='SET.programs')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='SET.year_level')),
            ],
        ),
        migrations.CreateModel(
            name='professor_subjs',
            fields=[
                ('prof_subjects_id', models.AutoField(primary_key=True, serialize=False)),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_subjects', to='SET.professor_info')),
                ('year_sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_subjects', to='SET.academic_yearsem')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_subjects', to='SET.section')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_subjects', to='SET.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='student_enrolled_subjs',
            fields=[
                ('student_enrolled_subj_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('prof_subj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='SET.professor_subjs')),
            ],
        ),
        migrations.CreateModel(
            name='numerical_ratings',
            fields=[
                ('numerical_id', models.AutoField(primary_key=True, serialize=False)),
                ('numerical_rating', models.PositiveSmallIntegerField()),
                ('numerical_date', models.DateField()),
                ('numerical_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerical_ratings', to='SET.numerical_questions')),
                ('student_subj_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numerical_ratings', to='SET.student_enrolled_subjs')),
            ],
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='student_subj_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='SET.student_enrolled_subjs'),
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='SET.section')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='SET.student_status')),
            ],
        ),
        migrations.AddField(
            model_name='student_enrolled_subjs',
            name='student_id',
            field=models.ForeignKey(default='21-00260', on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_subjects', to='SET.student_info'),
        ),
    ]
