# Generated by Django 5.0.7 on 2024-09-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academic_year',
            fields=[
                ('year_sem_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('academic_year_desc', models.CharField(max_length=20)),
                ('semester_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('department_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='professor_status',
            fields=[
                ('professor_status_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('professor_status_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_status',
            fields=[
                ('student_status_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('student_status_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subject_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='year_level',
            fields=[
                ('year_level_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('year_level_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='professor_info',
            fields=[
                ('professor_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.department')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.professor_status')),
            ],
        ),
        migrations.CreateModel(
            name='professor_current_subjs',
            fields=[
                ('prof_subj_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.academic_year')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.professor_info')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='student_enrolled_subjs',
            fields=[
                ('student_enrolled_subj_id', models.AutoField(primary_key=True, serialize=False)),
                ('units', models.PositiveIntegerField()),
                ('grades', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('prof_subj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.professor_current_subjs')),
                ('year_sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.academic_year')),
            ],
        ),
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=10)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.student_status')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.year_level')),
            ],
        ),
    ]
