# Generated by Django 5.0.7 on 2024-09-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='program',
            fields=[
                ('program_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('program_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='student_info',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.program'),
        ),
    ]
