# Generated by Django 5.0.7 on 2024-09-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0002_program_alter_student_info_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_enrolled_subjs',
            name='grades',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
