# Generated by Django 5.0.7 on 2024-09-09 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0003_alter_student_enrolled_subjs_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('category_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('category_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_questions',
            fields=[
                ('feedback_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='student_enrolled_subjs',
            name='units',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='year_level',
            name='year_level_id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='feedbacks',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('feedback_date', models.DateField()),
                ('feedback_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.feedback_questions')),
                ('prof_subj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.professor_current_subjs')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.student_info')),
            ],
        ),
        migrations.CreateModel(
            name='filtered_feedbacks',
            fields=[
                ('sentiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentiment_rating', models.IntegerField()),
                ('sentiment_label', models.CharField(max_length=12)),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.feedbacks')),
            ],
        ),
        migrations.CreateModel(
            name='numerical_questions',
            fields=[
                ('numerical_question_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.categories')),
            ],
        ),
        migrations.CreateModel(
            name='numerical_ratings',
            fields=[
                ('numerical_id', models.AutoField(primary_key=True, serialize=False)),
                ('numerical_rating', models.PositiveSmallIntegerField()),
                ('numerical_date', models.DateField()),
                ('numerical_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.numerical_questions')),
                ('prof_subj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.professor_current_subjs')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.student_info')),
            ],
        ),
    ]
