# Generated by Django 5.0.7 on 2024-10-04 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0003_alter_section_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='assoc_college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SET.department'),
        ),
    ]
