# Generated by Django 5.0.7 on 2024-09-09 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0004_categories_feedback_questions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='program',
            new_name='programs',
        ),
    ]
