# Generated by Django 5.0.7 on 2024-09-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0005_rename_program_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='program',
        ),
        migrations.DeleteModel(
            name='programs',
        ),
    ]
