# Generated by Django 5.0.7 on 2024-10-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0005_alter_feedbacks_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
