# Generated by Django 5.0.7 on 2024-09-09 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0006_remove_student_info_program_delete_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='programs',
            fields=[
                ('program_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('program_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student_info',
            name='program',
            field=models.ForeignKey(default='PLP', on_delete=django.db.models.deletion.CASCADE, to='SET.programs'),
        ),
    ]
