# Generated by Django 5.0.7 on 2024-09-09 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0007_programs_student_info_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_enrolled_subjs',
            name='student_id',
            field=models.ForeignKey(default='00-00000', on_delete=django.db.models.deletion.CASCADE, to='SET.student_info'),
        ),
    ]
