# Generated by Django 5.0.7 on 2024-10-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0011_alter_professor_subjs_prof_subjects_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='numerical_ratings',
            name='numerical_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor_subjs',
            name='prof_subjects_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_enrolled_subjs',
            name='student_enrolled_subj_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
