# Generated by Django 5.0.7 on 2024-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_acc',
            name='admin_acc_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_acc',
            name='student_acc_number',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student_info',
            name='student_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
