# Generated by Django 5.0.7 on 2024-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0002_alter_admin_acc_admin_acc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_acc',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student_info',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
