# Generated by Django 5.0.7 on 2024-09-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0003_student_acc_date_of_birth_student_info_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_info',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student_info',
            name='plp_email',
        ),
        migrations.AddField(
            model_name='student_acc',
            name='plp_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
