# Generated by Django 5.0.7 on 2024-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0004_remove_student_info_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_info',
        ),
        migrations.AlterField(
            model_name='student_acc',
            name='plp_email',
            field=models.EmailField(default='example_example@plpasig.edu.ph', max_length=254),
        ),
    ]
