# Generated by Django 5.0.7 on 2024-10-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0003_alter_section_section'),
        ('userLogin', '0005_delete_student_info_alter_student_acc_plp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_acc',
            name='dept_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SET.department'),
        ),
        migrations.AddField(
            model_name='admin_acc',
            name='is_mis',
            field=models.BooleanField(default=False),
        ),
    ]
