"""
Django settings for django_plpSET project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'userLogin',
    'SET',
    'reportsAnalysis',
    'django_celery_beat',

    
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(",")

CORS_ALLOWED_ORIGINS = ["https://sentiment-professor-feedback.vercel.app", "https://sentiment-professor-feedback-1.onrender.com"]  
CSRF_TRUSTED_ORIGINS = ['https://sentiment-professor-feedback.vercel.app', 'https://sentiment-professor-feedback-1.onrender.com' ]  


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backendSet.urls'




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                
            ],
        },
    },
]

WSGI_APPLICATION = 'backendSet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'plpset',
        'USER': 'plpsetadmin',
        'PASSWORD': 'plpset_admin',
        'HOST': 'localhost',   
        'PORT': '3306',       
    }
}

DATABASES["default"] = dj_database_url.parse(config("DATABASE_URL"))
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session expiration 
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database-backed sessions
SESSION_COOKIE_NAME = 'sessionid'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True  # Set to True if using HTTPS
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire session when the browser closes
SESSION_COOKIE_SAMESITE = 'None'


# Celery settings

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

CELERY_BROKER_URL = 'rediss://red-csoq419u0jms738nvmsg:UUjd3PJnwwAakCWdRggOTbmM5mtEzgB1@oregon-redis.render.com:6379/0?ssl_cert_reqs=CERT_NONE'
CELERY_RESULT_BACKEND = 'rediss://red-csoq419u0jms738nvmsg:UUjd3PJnwwAakCWdRggOTbmM5mtEzgB1@oregon-redis.render.com:6379/0?ssl_cert_reqs=CERT_NONE'



# Celery Beat
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'update_summaries_every_15mins': {
        'task': 'SET.tasks.update_summaries_batch',  
        'schedule': crontab(minute='*/15',),    
    },
    'update_professor_recurring_phrases': {
        'task': 'SET.tasks.update_professor_recurring_phrases',
        'schedule': crontab(minute='*/15'),  
    },
    'count_total_submissions': {
        'task': 'SET.tasks.count_total_submissions',
        'schedule': crontab(minute='*/15'),  
    },
}
