# Generated by Django 5.0.7 on 2024-10-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SET', '0007_delete_filtered_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='filtered_feedbacks',
            fields=[
                ('sentiment_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentiment_rating', models.IntegerField()),
                ('sentiment_label', models.CharField(max_length=12)),
                ('analysis_date', models.DateField(null=True)),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtered_feedbacks', to='SET.feedbacks')),
            ],
        ),
    ]
