# Generated by Django 5.0.7 on 2024-10-14 19:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0013_remove_feedbacks_pre_processed_text'),
        ('reportsAnalysis', '0002_training_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='processed_feedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_text', models.TextField()),
                ('processed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('feedback_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.feedbacks')),
            ],
        ),
    ]
