# Generated by Django 3.2 on 2024-10-18 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0013_remove_feedbacks_pre_processed_text'),
        ('reportsAnalysis', '0003_processed_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='numerical_summary',
            fields=[
                ('numerical_summary_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('average', models.FloatField()),
                ('numerical_questions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.numerical_questions')),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.professor_info')),
                ('year_sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.academic_yearsem')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_summary',
            fields=[
                ('feedback_summary_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('total_feedbacks', models.IntegerField()),
                ('total_positive', models.IntegerField()),
                ('total_negative', models.IntegerField()),
                ('total_neutral', models.IntegerField()),
                ('feedback_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.feedback_questions')),
                ('prof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.professor_info')),
                ('year_sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.academic_yearsem')),
            ],
        ),
    ]
