# Generated by Django 3.2 on 2024-10-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsAnalysis', '0005_auto_20241021_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor_numerical_summary_questions',
            old_name='numerical_questions_id',
            new_name='numerical_question_id',
        ),
    ]
