# Generated by Django 3.2 on 2024-10-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsAnalysis', '0006_rename_numerical_questions_id_professor_numerical_summary_questions_numerical_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor_feedback_total',
            name='professor_feedback_total_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
