# Generated by Django 3.2 on 2024-10-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsAnalysis', '0008_alter_professor_numerical_total_professor_numerical_total_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtered_feedbacks',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
