# Generated by Django 3.2 on 2024-10-22 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsAnalysis', '0009_filtered_feedbacks_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtered_feedbacks',
            name='analysis_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
