# Generated by Django 3.2 on 2024-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsAnalysis', '0010_alter_filtered_feedbacks_analysis_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='processed_feedbacks',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processed_feedbacks',
            name='recurring_phrases',
            field=models.ManyToManyField(blank=True, to='reportsAnalysis.RecurringPhrase'),
        ),
    ]
