# Generated by Django 3.2 on 2024-10-31 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0016_professor_info_extension_name'),
        ('reportsAnalysis', '0011_auto_20241101_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringphrase',
            name='count',
        ),
        migrations.AddField(
            model_name='recurringphrase',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SET.department'),
        ),
        migrations.AddField(
            model_name='recurringphrase',
            name='negative_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringphrase',
            name='neutral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringphrase',
            name='positive_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringphrase',
            name='prof_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SET.professor_info'),
        ),
        migrations.AddField(
            model_name='recurringphrase',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recurringphrase',
            name='year_sem_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SET.academic_yearsem'),
        ),
        migrations.AlterField(
            model_name='recurringphrase',
            name='phrase',
            field=models.CharField(max_length=255),
        ),
    ]
