# Generated by Django 3.2 on 2024-10-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsAnalysis', '0012_auto_20241101_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringphrase',
            old_name='negative_count',
            new_name='sentiment_rating',
        ),
        migrations.RemoveField(
            model_name='recurringphrase',
            name='neutral_count',
        ),
        migrations.RemoveField(
            model_name='recurringphrase',
            name='positive_count',
        ),
        migrations.AddField(
            model_name='recurringphrase',
            name='sentiment_label',
            field=models.CharField(default='Neutral', max_length=12),
        ),
    ]
