# Generated by Django 3.2 on 2024-10-31 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsAnalysis', '0013_auto_20241101_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='processed_feedbacks',
            name='analysis_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
