# Generated by Django 3.2 on 2024-10-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsAnalysis', '0014_processed_feedbacks_analysis_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processed_feedbacks',
            name='analysis_date',
        ),
    ]
