# Generated by Django 3.2 on 2024-11-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SET', '0021_auto_20241102_1814'),
        ('reportsAnalysis', '0015_remove_processed_feedbacks_analysis_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='college_numerical_summary_questions',
            fields=[
                ('college_numerical_summary_question_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('college_question_average', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.categories')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.department')),
                ('numerical_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.numerical_questions')),
                ('year_sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SET.academic_yearsem')),
            ],
        ),
    ]
